CREATE DATABASE go_todo;

USE go_todo;

create table if not exists User (user_id INT AUTO_INCREMENT, email VARCHAR(256) NOT NULL, password VARCHAR(256) NOT NULL, created_at DATETIME  DEFAULT CURRENT_TIMESTAMP,last_login DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (user_id), UNIQUE (email) ) ENGINE = INNODB, CHARACTER SET = utf8mb4, COLLATE utf8mb4_general_ci;

create table if not exists Todo (todo_id INT AUTO_INCREMENT,content VARCHAR(512) NOT NULL, created_at DATETIME NOT NULL  DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (todo_id) ) ENGINE = INNODB, CHARACTER SET = utf8mb4, COLLATE utf8mb4_general_ci;