name: Go

on: pull_request

jobs:
  goone:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt update && sudo apt install build-essential libnetfilter-queue-dev libnfnetlink-dev
      - name: Set up Go 1.15.3
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.3
        id: go
      - name: install goone
        run: go get -u github.com/masibw/goone/cmd/go_one
      - name: run goone
        run: go vet -vettool=`which go_one` -go_one.configPath="$PWD/go_one.yml" ./...